name = "redesaudemais"
compatibility_date = "2025-03-01"
compatibility_flags = ["nodejs_compat"]

# Worker main gerado pelo OpenNext
main = ".open-next/worker.js"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"
not_found_handling = "single-page-application"

# Observability opcional
[observability]
enabled = true
